export const metadata = {
  title: "NEXT.js",
  description: "generated by next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body>{children}</body>
    </html>
  );
}
