import vazirFont from "@/constants/localFont";
import "./globals.css";

export const metadata = {
  title: "Next Shop Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body className={`${vazirFont.variable} font-sans`}>{children}</body>
    </html>
  );
}
