import vazirFont from "@/constants/localFont";
import "./globals.css";
import Header from "./Header";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Next Shop Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirFont.variable} font-sans min-h-screen `}>
        <Toaster />
        <Header />
        <div className="container xl:max-w-screen-xl mx-auto">{children}</div>
      </body>
    </html>
  );
}
